//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 편집기의_제왕.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("편집기의_제왕.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   a-frame|3970000
        ///a-sub|6170000
        ///a.b.s.|16200000
        ///a.c.i.s.|569000
        ///a.c.l.s.|882000
        ///a.c.u.|1030000
        ///a.d.|160000000
        ///a.e.r.e.|215000
        ///a.m.|457000000
        ///a.v.c.|826000
        ///aardvark|1090000
        ///aaron|20300000
        ///abaca|209000
        ///abaci|48700
        ///aback|645000
        ///abacus|1900000
        ///abac|330000
        ///abaddon|216000
        ///abaft|45600
        ///abalone|628000
        ///abampere|5680
        ///abandoned|17400000
        ///abandonee|801
        ///abandoner|10400
        ///abandonment|3480000
        ///abandon|9410000
        ///abasement|213000
        ///abase|111000
        ///abashment|9580
        ///abash|35500
        ///abasia|15500
        ///abas|477000
        ///abateme[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string google {
            get {
                return ResourceManager.GetString("google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All kinds of||a.모든 종류의
        ///Los||def. 스페인어의 &apos;the&apos;에 해당하는 말
        ///angeles||n.스페인어로 &apos;천사들&apos;이라는 말
        ///so to speak||말하자면
        ///reinvent the wheel||(이미 있는 것을 다시 만드느라) 쓸데없이 시간을 낭비하다
        ///on a continual basis||계속적으로
        ///think through||~을 충분히 생각하다
        ///public agency||n.공공 기관
        ///financial center||n.금융 중심지
        ///go beyond||~을 넘어서다, ~을 초과하다
        ///take to heart||진지하게 받아들이다
        ///homeownership||n.주택 소유
        ///predatory lending||n.약탈적 대출`(상환 능력 이상으로 대출해 주고 이득을 취하는 것)
        ///inevitably||ad.불가피하게, 필연적으로
        ///human capital||n.인적 자본
        ///industrial might||n.산업 역량
        ///outsource||외부에 위탁하다
        ///at a f[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string word01t {
            get {
                return ResourceManager.GetString("word01t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 느낌_비활성화 {
            get {
                object obj = ResourceManager.GetObject("느낌_비활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 느낌_활성화 {
            get {
                object obj = ResourceManager.GetObject("느낌_활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 보기1 {
            get {
                object obj = ResourceManager.GetObject("보기1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 보기1_해설 {
            get {
                object obj = ResourceManager.GetObject("보기1_해설", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 보기2 {
            get {
                object obj = ResourceManager.GetObject("보기2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 보기2_해설 {
            get {
                object obj = ResourceManager.GetObject("보기2_해설", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 보기3 {
            get {
                object obj = ResourceManager.GetObject("보기3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 보기3_해설 {
            get {
                object obj = ResourceManager.GetObject("보기3_해설", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 보기4 {
            get {
                object obj = ResourceManager.GetObject("보기4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 보기4_해설 {
            get {
                object obj = ResourceManager.GetObject("보기4_해설", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 보기5 {
            get {
                object obj = ResourceManager.GetObject("보기5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 보기5_해설 {
            get {
                object obj = ResourceManager.GetObject("보기5_해설", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 본문 {
            get {
                object obj = ResourceManager.GetObject("본문", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 빈칸_비활성화 {
            get {
                object obj = ResourceManager.GetObject("빈칸_비활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 빈칸_활성화 {
            get {
                object obj = ResourceManager.GetObject("빈칸_활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 사전_배경 {
            get {
                object obj = ResourceManager.GetObject("사전_배경", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 어법_비활성화 {
            get {
                object obj = ResourceManager.GetObject("어법_비활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 어법_활성화 {
            get {
                object obj = ResourceManager.GetObject("어법_활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 어휘 {
            get {
                object obj = ResourceManager.GetObject("어휘", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 어휘_비활성화 {
            get {
                object obj = ResourceManager.GetObject("어휘_비활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 어휘_활성화 {
            get {
                object obj = ResourceManager.GetObject("어휘_활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   deny
        ///ought
        ///ammonia
        ///nail
        ///eats
        ///dentist
        ///footwear
        ///rid
        ///guitar
        ///ginseng
        ///planet
        ///spoke
        ///freelance
        ///comedian
        ///grandfather
        ///dirt
        ///nymph
        ///herself
        ///rock-climbing
        ///peach
        ///cicada
        ///candle
        ///raft
        ///twelfth
        ///magma
        ///volcano
        ///iced
        ///hundred
        ///nile
        ///bacha
        ///posh
        ///united
        ///states
        ///soviet
        ///union
        ///twitter
        ///UNICEF
        ///Alex
        ///Columbus
        ///Gee
        ///ex
        ///Homo
        ///sapiens
        ///Tsar
        ///tsar
        ///Jekyll
        ///Hyde
        ///Crow
        ///Pinta
        ///Nina
        ///Santa
        ///Maria
        ///Eunuch
        ///Chaldean
        ///Copernicus
        ///sixteen
        ///Ninety
        ///eighty
        ///Mark
        ///Twain
        ///Ernest
        ///Hemingway
        ///Edwin
        ///Arlington
        ///Robinson
        ///C[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 어휘빈칸예외단어 {
            get {
                return ResourceManager.GetString("어휘빈칸예외단어", resourceCulture);
            }
        }
        
        /// <summary>
        ///   things|thing
        ///abandoned|abandon
        ///abandoning|abandon
        ///abased|abase
        ///abasing|abase
        ///abated|abate
        ///abating|abate
        ///abbreviated|abbreviate
        ///abbreviating|abbreviate
        ///abdicated|abdicate
        ///abdicating|abdicate
        ///abducted|abduct
        ///abducting|abduct
        ///abetted|abet
        ///abetting|abet
        ///abhorred|abhor
        ///abhorring|abhor
        ///abided|abide
        ///abiding|abide
        ///abolished|abolish
        ///abolishing|abolish
        ///aborted|abort
        ///aborting|abort
        ///abounded|abound
        ///abounding|abound
        ///about-faced|about-face
        ///about-facing|about-face
        ///abridged|abridge
        ///abridging|abr[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 원형탐지기 {
            get {
                return ResourceManager.GetString("원형탐지기", resourceCulture);
            }
        }
        
        /// <summary>
        ///   done|do
        ///had|have
        ///been|be
        ///arisen|arise
        ///came|come
        ///lain|lie
        ///swum|swim
        ///shrunk|shrink
        ///sung|sing
        ///withdrawn|withdraw
        ///sunken|sink
        ///sunk|sink
        ///forgiven|forgive
        ///bidden|bid
        ///hurt|hurt
        ///thrust|thrust
        ///broadcast|broadcast
        ///risen|rise
        ///fallen|fall
        ///split|split
        ///spread|spread
        ///fitted|fit
        ///shut|shut
        ///cast|cast
        ///eaten|eat
        ///broken|break
        ///flown|fly
        ///driven|drive
        ///woken|wake
        ///beaten|beat
        ///ridden|ride
        ///rung|ring
        ///hidden|hide
        ///struck|strike
        ///stricken|strike
        ///frozen|freeze
        ///drawn|draw
        ///sprung|spring
        ///run|run
        ///hit|hit
        ///[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 원형탐지기ed {
            get {
                return ResourceManager.GetString("원형탐지기ed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   doing|do
        ///having|have
        ///being|be
        ///arising|arise
        ///coming|come
        ///lying|lie
        ///swimming|swim
        ///shrinking|shrink
        ///singing|sing
        ///withdrawing|withdraw
        ///sinking|sink
        ///sinking|sink
        ///forgiving|forgive
        ///bidding|bid
        ///hurting|hurt
        ///thrusting|thrust
        ///broadcasting|broadcast
        ///rising|rise
        ///falling|fall
        ///splitting|split
        ///spreading|spread
        ///fitting|fit
        ///shutting|shut
        ///casting|cast
        ///eating|eat
        ///breaking|break
        ///flying|fly
        ///driving|drive
        ///waking|wake
        ///beating|beat
        ///riding|ride
        ///ringing|ring
        ///hiding|hide
        ///striking|strike
        ///striking|str[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 원형탐지기ing {
            get {
                return ResourceManager.GetString("원형탐지기ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 일치_비활성화 {
            get {
                object obj = ResourceManager.GetObject("일치_비활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 일치_활성화 {
            get {
                object obj = ResourceManager.GetObject("일치_활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   abandon
        ///aboard
        ///abrupt
        ///abruptly
        ///absolute
        ///absolutely
        ///absorb
        ///absorption
        ///abstract
        ///abstraction
        ///absurd
        ///accentuate
        ///accompany
        ///accomplish
        ///accomplishment
        ///accord
        ///accordance
        ///according
        ///accordingly
        ///accuracy
        ///accurate
        ///accuse
        ///accustomed
        ///ache
        ///acquire
        ///acre
        ///ad
        ///adapt
        ///adaptation
        ///adequate
        ///adjust
        ///admire
        ///adolescence
        ///adolescent
        ///adopt
        ///adversity
        ///advertise
        ///advertisement
        ///advertiser
        ///affection
        ///afflict
        ///afford
        ///afterward
        ///agency
        ///agricultural
        ///agriculture
        ///algebra
        ///algebraic
        ///ally
        ///aloud
        ///alphabetic        ///[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 잘못된보기들 {
            get {
                return ResourceManager.GetString("잘못된보기들", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 제목 {
            get {
                object obj = ResourceManager.GetObject("제목", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 주관식 {
            get {
                object obj = ResourceManager.GetObject("주관식", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 주관식_해설 {
            get {
                object obj = ResourceManager.GetObject("주관식_해설", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 주제_비활성화 {
            get {
                object obj = ResourceManager.GetObject("주제_비활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 주제_활성화 {
            get {
                object obj = ResourceManager.GetObject("주제_활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 지시_비활성화 {
            get {
                object obj = ResourceManager.GetObject("지시_비활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 지시_활성화 {
            get {
                object obj = ResourceManager.GetObject("지시_활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 질문 {
            get {
                object obj = ResourceManager.GetObject("질문", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 해석 {
            get {
                object obj = ResourceManager.GetObject("해석", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 흐름_비활성화 {
            get {
                object obj = ResourceManager.GetObject("흐름_비활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 흐름_활성화 {
            get {
                object obj = ResourceManager.GetObject("흐름_활성화", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 힌트 {
            get {
                object obj = ResourceManager.GetObject("힌트", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
